version: "3.1"
services:
    db:
        image: postgres
        restart: always
        ports:
            - 5432:5432
        environment:
            - POSTGRES_PASSWORD=cgapp-password
            - POSTGRES_USER=postgres
            - POSTGRES_DB=cgapp-postgres
#   api:
#     build:
#       context: ../backend/api
#       dockerfile: ./Dockerfile
#     restart: on-failure
#     environment:
#       - JWT_SECRET_KEY="secret"
#       - JWT_SECRET_KEY_EXPIRE_MINUTES_COUNT=15
#       - JWT_REFRESH_KEY="refresh"
#       - JWT_REFRESH_KEY_EXPIRE_HOURS_COUNT=720
#       - SERVER_HOST=0.0.0.0
#       - SERVER_PORT=5001
#       - SERVER_READ_TIMEOUT=60
#       - STAGE_STATUS="dev"
#     ports:
#       - 5001:5001
#     # command: sh -c "sleep 10;"
  
#   fe:
#     build:
#       context: ../frontend/frontend-typescript
#       dockerfile: ./Dockerfile
#     depends_on:
#       - api
#     restart: on-failure
#     environment:
#       - API_BASE_URL=api:5001
#     ports:
#       - 3000:3000
#     # command: sh -c "sleep 10;"
