-- Delete tables
DROP TABLE IF EXISTS region;
DROP TABLE IF EXISTS languages;
DROP TABLE IF EXISTS role;
DROP TABLE IF EXISTS member;
DROP TABLE IF EXISTS member_m2m_fa;
DROP TABLE IF EXISTS tenant;
DROP TABLE IF EXISTS tenant_language;
DROP TABLE IF EXISTS tenant_member;